# Generated by Django 3.1 on 2020-08-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='Honorarios'),
        ),
    ]
